---
title: "Feeding trials"
author: "Julianna Renzi"
date: "11/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse) # data wrangling
require(here) # relative file paths
require(wesanderson) # colors
```

# Bring in the data

```{r}
algalFeed <- read_csv(here("data/Algal_feeding_trial.csv"))

```

Summarize the data in terms of percent loss

```{r}
algalFeed %>% 
  mutate(Algal_loss = Initial_weight_g - Final_weight_g) %>% 
  mutate(Percent_loss = Algal_loss / Initial_weight_g * 100) %>% 
  filter(!is.na(Algal_loss)) %>% 
  filter(Species != "Chlorodiella") -> percLoss
```

Create our color palette from the Wes Anderson package

```{r}
vibRed <- wes_palette("Darjeeling1", n = 5)[1]
forGreen <- wes_palette("Darjeeling1", n = 5)[2]
lightO <- wes_palette("Darjeeling1", n = 5)[3]
darkO <- wes_palette("Darjeeling1", n = 5)[4]
skyB <- wes_palette("Darjeeling1", n = 5)[5]

```

# Plot results

```{r} 
# pdf(here("figures/algalFeedTrial.pdf"), width = 6, height = 5)

percLoss %>% 
  ggplot(aes(x = Species, y = Percent_loss, fill = Species)) +
  geom_violin(color = NA) + 
  scale_fill_manual(values = c(lightO, skyB)) +
  labs(y="Percent loss of algal biomass", x = "Treatment") +
  geom_point() +
  theme_classic() +
  theme(text = element_text(size=15)) +
  stat_summary(geom = 'text', label = c("a", "b"), 
               fun.y = max, vjust = -1, size=6, 
               color = c(lightO, skyB)) +
  
  ylim(15,80) +
  theme(legend.position = "none")

# dev.off()

```

# Test statistically

First check assumptions

```{r}
# but still should test
percLoss %>% 
  filter(Species == "Cyclodius") -> cyclFeed

percLoss %>% 
  filter(Species == "Control") -> ctrlFeed

par(mfrow=c(1,2))
qqnorm(ctrlFeed$Algal_loss)
qqline(ctrlFeed$Algal_loss)
qqnorm(cyclFeed$Algal_loss)
qqline(cyclFeed$Algal_loss) # Normal so t-test is legitimate
shapiro.test(cyclFeed$Algal_loss) # Normal
shapiro.test(ctrlFeed$Algal_loss) # Normal
  var.test(cyclFeed$Algal_loss, ctrlFeed$Algal_loss) # variances borderline but OK

par(mfrow=c(1,2))
qqnorm(ctrlFeed$Percent_loss)
qqline(ctrlFeed$Percent_loss)
qqnorm(cyclFeed$Percent_loss)
qqline(cyclFeed$Percent_loss) # Normal so t-test is legitimate
shapiro.test(cyclFeed$Percent_loss) 
shapiro.test(cyclFeed$Percent_loss) # Normal
  var.test(cyclFeed$Percent_loss, cyclFeed$Percent_loss) # variances not equal

```

Run t-tests

```{r}
t.test(ctrlFeed$Algal_loss, cyclFeed$Algal_loss, 
       var.equal = FALSE, 
       alternative = "two.sided") # significant
t.test(ctrlFeed$Percent_loss, 
       cyclFeed$Percent_loss, 
       var.equal = FALSE, alternative = "two.sided") # significant
```

# Summary stats

```{r}
## Summary stats----
percLoss %>% 
  summarize(N = n(), 
            Mean_inital_g = mean(Initial_weight_g), 
            sd_inital_g = sd(Initial_weight_g))

percLoss %>% 
  group_by(Species) %>% 
  summarize(N = n(), 
            Mean_carapace = mean(Carapace_mm), 
            sd_carapace = sd(Carapace_mm),
            Mean_algal_loss = mean(Algal_loss), 
            sd_algal_loss = sd(Algal_loss),
            Mean_perc_algal_loss = mean(Percent_loss), 
            sd_perc_algal_loss = sd(Percent_loss)) 
```




